# Generated by Django 4.1.4 on 2022-12-26 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models_db', '0002_origen_video_estructura_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_db.estado_video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_db.origen_video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
