# Generated by Django 4.1.5 on 2023-01-20 18:20

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('models_db', '0004_video_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='imagen',
            field=models.ImageField(default='https://www.elcineenlasombra.com/wp-content/uploads/2018/10/pelicula-rodar-FB.jpg', upload_to=pathlib.PureWindowsPath('D:/Proyectos_Particulares/Ver_Videos/app/static/img')),
        ),
    ]
