# Generated by Django 4.1.5 on 2023-01-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_db', '0014_alter_video_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='imagen',
        ),
    ]
